version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: mongodb-memory-server
    versions:
    - 6.9.3
  - dependency-name: twilio
    versions:
    - 3.51.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: pug
    versions:
    - 3.0.0
