language: node_js
node_js:
- '4.2'
install:
- npm install
services: mongodb
env:
  global:
    - TWILIO_ACCOUNT_SID=Your-Account-SID
    - TWILIO_AUTH_TOKEN=Your-Twilio-Authy-Token
    - TWILIO_NUMBER=Your-Twilio-Phone-Number
